/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/steklo.glb
Author: alex123iuyt (https://sketchfab.com/alex123iuyt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/steklo-a0fa691b97744f57b19febf6193f4b8e
Title: steklo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/steklo.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['23_Scene_-_Root_0'].geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes['23_Scene_-_Root_0_1'].geometry} material={materials['Scene_-_Root']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['16_Scene_-_Root_0'].geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes['16_Scene_-_Root_0_1'].geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes['16_Scene_-_Root_0_2'].geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes['16_Scene_-_Root_0_3'].geometry} material={materials['Scene_-_Root']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['9_Scene_-_Root_0'].geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes['9_Scene_-_Root_0_1'].geometry} material={materials['Scene_-_Root']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['2_Scene_-_Root_0'].geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes['2_Scene_-_Root_0_1'].geometry} material={materials['Scene_-_Root']} />
        </group>
        <mesh geometry={nodes['30_Scene_-_Root_0'].geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/steklo.glb')
