/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 src\components\box\model.glb
Author: Urpo (https://sketchfab.com/Urpo)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/mechanical-keyboard-1facc22c744a403dbb3166a2274f78dd
Title: Mechanical Keyboard
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("./model.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials["03___Default"]}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials["09___Default"]}
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials["02___Default"]}
          />
          <mesh
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials["08___Default"]}
          />
          <mesh
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials["07___Default"]}
          />
          <mesh
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials["01___Default"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./model.glb");
