/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 src\components\box\model.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("./model.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes["16_Scene_-_Root_0"].geometry}
            material={materials["Scene_-_Root"]}
          />
          <mesh
            geometry={nodes["16_Scene_-_Root_0001"].geometry}
            material={materials["Scene_-_Root"]}
          />
          <mesh
            geometry={nodes["16_Scene_-_Root_0002"].geometry}
            material={materials["Scene_-_Root"]}
          />
          <mesh
            geometry={nodes["16_Scene_-_Root_0003"].geometry}
            material={materials["Scene_-_Root"]}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes["2_Scene_-_Root_0"].geometry}
            material={materials["Scene_-_Root"]}
          />
          <mesh
            geometry={nodes["2_Scene_-_Root_0001"].geometry}
            material={materials["Scene_-_Root"]}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes["23_Scene_-_Root_0"].geometry}
            material={materials["Scene_-_Root"]}
          />
          <mesh
            geometry={nodes["23_Scene_-_Root_0001"].geometry}
            material={materials["Scene_-_Root"]}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes["9_Scene_-_Root_0"].geometry}
            material={materials["Scene_-_Root"]}
          />
          <mesh
            geometry={nodes["9_Scene_-_Root_0001"].geometry}
            material={materials["Scene_-_Root"]}
          />
        </group>
        <mesh
          geometry={nodes["30_Scene_-_Root_0"].geometry}
          material={materials["Scene_-_Root"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./model.gltf");
